# Generated by Django 4.2.16 on 2026-06-16 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_kk', models.CharField(max_length=120)),
                ('title_ru', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('emoji', models.CharField(blank=True, default='🗣️', max_length=16)),
                ('category', models.CharField(choices=[('NEEDS', 'Потребности'), ('EMOTIONS', 'Эмоции'), ('ACTIONS', 'Действия'), ('FOOD', 'Еда'), ('PLACES', 'Места')], default='NEEDS', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Карточка коммуникации',
                'verbose_name_plural': 'Карточки коммуникации',
                'ordering': ['category', 'title_ru'],
            },
        ),
    ]
