# Generated by Django 4.2.16 on 2026-06-16 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='children.childprofile')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_kk', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default='📌', max_length=16)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='schedule_icons/')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Выполнено'), ('SKIPPED', 'Пропущено')], default='PENDING', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_suggested', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Элемент расписания',
                'verbose_name_plural': 'Элементы расписания',
                'ordering': ['order', 'start_time'],
            },
        ),
    ]
