# Generated by Django 4.2.16 on 2026-06-16 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка'), ('REFUNDED', 'Возврат')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('KASPI', 'Kaspi Pay'), ('CARD', 'Карта'), ('TRANSFER', 'Перевод')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('FREE', 'Бесплатный'), ('OTBASY', 'Отбасы'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=12, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_children', models.IntegerField(blank=True, null=True)),
                ('max_cards', models.IntegerField(blank=True, null=True)),
                ('schedule_any_date', models.BooleanField(default=False)),
                ('has_behavior_log', models.BooleanField(default=False)),
                ('has_realtime', models.BooleanField(default=False)),
                ('has_pdf_export', models.BooleanField(default=False)),
                ('has_ai', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('multi_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_contact_sales', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('CANCELLED', 'Отменена'), ('EXPIRED', 'Истекла'), ('TRIAL', 'Пробный период')], default='ACTIVE', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Ежемесячно'), ('YEARLY', 'Ежегодно')], default='MONTHLY', max_length=8)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=10)),
                ('commission_percent', models.PositiveSmallIntegerField(default=20)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реферальный код',
                'verbose_name_plural': 'Реферальные коды',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Платёжное событие',
                'verbose_name_plural': 'Платёжные события (audit)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription'),
        ),
    ]
