# Generated by Django 4.2.16 on 2026-06-16 07:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('mood', models.PositiveSmallIntegerField(help_text='Настроение от 1 (плохо) до 5 (отлично)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('triggers', models.TextField(blank=True, help_text='Что вызвало стресс')),
                ('positive_moments', models.TextField(blank=True, help_text='Позитивные моменты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_insights', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Запись дневника поведения',
                'verbose_name_plural': 'Дневник поведения',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
