# Generated by Django 4.2.16 on 2026-06-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='children.childprofile'),
        ),
    ]
